// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_DISABLED_MESSAGE =
  'Supabase no está configurado en este entorno. Las funciones de almacenamiento (envío de archivos) están deshabilitadas.';

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(`[Supabase] ${SUPABASE_DISABLED_MESSAGE}`);
    return null;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createClient<Database>> | null | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// Returns a Proxy that lazily creates the real client; if env vars are missing,
// any property access throws a clear, user-facing error instead of crashing at boot.
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop, receiver) {
    if (_supabase === undefined) _supabase = createSupabaseClient();
    if (_supabase === null) {
      throw new Error(SUPABASE_DISABLED_MESSAGE);
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});

export const isSupabaseConfigured = Boolean(
  import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
);
